version: '2'
services:
  dev-image:
    image: "loic-yvo/ubuntu/gcc-ranges:7.4"
    ports:
      - "2000:2000"
    privileged: true
    container_name: devenv
    volumes:
      - "../..:/home/develop/dev"
